const List transactionCategories = [
  {"name": "Auto", "icon": "assets/images/Auto.png"},
  {"name": "Bank", "icon": "assets/images/Bank.png"},
  {"name": "Cash", "icon": "assets/images/Cash.png"},
  {"name": "Donation", "icon": "assets/images/Donation.png"},
  {"name": "Education", "icon": "assets/images/Education.png"},
  {"name": "Entertain", "icon": "assets/images/Entertain.png"},
  {"name": "Exercise", "icon": "assets/images/Exercise.png"},
  {"name": "Food", "icon": "assets/images/Food.png"},
  {"name": "Groceries", "icon": "assets/images/Groceries.png"},
  {"name": "Gift", "icon": "assets/images/Gift.png"},
  {"name": "Health", "icon": "assets/images/Health.png"},
  {"name": "Internet", "icon": "assets/images/Internet.png"},
  {"name": "Misc", "icon": "assets/images/Misc.png"},
  {"name": "Pets", "icon": "assets/images/Pets.png"},
  {"name": "Savings", "icon": "assets/images/Savings.png"},
  {"name": "Shopping", "icon": "assets/images/Shopping.png"},
  {"name": "Tech", "icon": "assets/images/Tech.png"},
  {"name": "Transfer", "icon": "assets/images/Transfer.png"},
  {"name": "Transport", "icon": "assets/images/Transport.png"},
  {"name": "Utilities", "icon": "assets/images/Utilities.png"},
];

const List budgetCategories = [
  {"name": "General", "icon": "assets/images/General.png"},
  {"name": "Auto", "icon": "assets/images/Auto.png"},
  {"name": "Bank", "icon": "assets/images/Bank.png"},
  {"name": "Cash", "icon": "assets/images/Cash.png"},
  {"name": "Donation", "icon": "assets/images/Donation.png"},
  {"name": "Education", "icon": "assets/images/Education.png"},
  {"name": "Entertain", "icon": "assets/images/Entertain.png"},
  {"name": "Exercise", "icon": "assets/images/Exercise.png"},
  {"name": "Food", "icon": "assets/images/Food.png"},
  {"name": "Groceries", "icon": "assets/images/Groceries.png"},
  {"name": "Gift", "icon": "assets/images/Gift.png"},
  {"name": "Health", "icon": "assets/images/Health.png"},
  {"name": "Internet", "icon": "assets/images/Internet.png"},
  {"name": "Misc", "icon": "assets/images/Misc.png"},
  {"name": "Pets", "icon": "assets/images/Pets.png"},
  {"name": "Savings", "icon": "assets/images/Savings.png"},
  {"name": "Shopping", "icon": "assets/images/Shopping.png"},
  {"name": "Tech", "icon": "assets/images/Tech.png"},
  {"name": "Transfer", "icon": "assets/images/Transfer.png"},
  {"name": "Transport", "icon": "assets/images/Transport.png"},
  {"name": "Utilities", "icon": "assets/images/Utilities.png"},
];
